### ISSUE TITLE
EVM tracing not available for tests

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-contracts#25]
The Buidler EVM we use for testing supports solidity stack traces. In our setup the tracing does not work, however. We get the following message
```
The Buidler EVM tracing engine could not be initialized. Run Buidler with --verbose to learn more.
  buidler:core:buidler-evm:node Buidler EVM tracing disabled: ContractsIdentifier failed to be initialized. Please report this to help us improve Buidler.
  buidler:core:buidler-evm:node  TypeError: Cannot read property 'startsWith' of undefined
    at toCanonicalAbiType (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:474:12)
    at astFunctionDefinitionToSelector (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:453:21)
    at processFunctionDefinitionAstNode (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:179:9)
    at processContractAstNode (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:126:7)
    at createSourcesModelFromAst (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:80:7)
    at Object.createModelsAndDecodeBytecodes (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/stack-traces/compiler-to-model.ts:32:3)
    at new BuidlerNode (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/node.ts:322:25)
    at Function.create (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/node.ts:228:18)
    at BuidlerEVMProvider._init (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:269:28)
    at BuidlerEVMProvider._send (radicle-contracts/node_modules/@nomiclabs/buidler/src/internal/buidler-evm/provider/provider.ts:188:5) +0ms
```

**Comment by CodeSandwich** [comment]
Reported on Buidler side: https://github.com/nomiclabs/buidler/issues/924
